"""Regression fixtures for the RQ2/RQ3 bootstrap scripts.

Slow (~1-2 min each, ~3-4 min total) and data-dependent (needs the real
run artifacts already committed under experiments/results/), so this lives
outside tests/unit and is NOT part of the default CI unit-tests job or
`make test` -- run explicitly via `make test-regression` before touching
compute_ablation_bootstrap.py / compute_rq3_kappa_bootstrap.py /
bootstrap_ci.py, to confirm no number silently changed.

The golden fixtures were generated by running each script against the real
committed data and diffing the output against the pre-refactor baseline
(byte-identical) when bootstrap_ci.py was extracted -- see
experiments/bootstrap_ci.py's docstring for the history.
"""

from __future__ import annotations

import json
import os
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent.parent
FIXTURES_DIR = Path(__file__).parent / "fixtures"


def _run_script_and_load_new_json(script: str, output_dir: Path, glob_pattern: str) -> dict:
    before = set(output_dir.glob(glob_pattern))

    env = {**os.environ, "PYTHONIOENCODING": "utf-8"}
    result = subprocess.run(
        [sys.executable, script],
        cwd=REPO_ROOT,
        env=env,
        capture_output=True,
        text=True,
        timeout=300,
    )
    assert result.returncode == 0, f"{script} failed:\n{result.stdout}\n{result.stderr}"

    after = set(output_dir.glob(glob_pattern))
    new_files = after - before
    assert len(new_files) == 1, f"expected exactly one new file, got {new_files}"
    new_file = new_files.pop()
    try:
        return json.loads(new_file.read_text(encoding="utf-8"))
    finally:
        new_file.unlink()


def test_ablation_bootstrap_matches_golden_output() -> None:
    actual = _run_script_and_load_new_json(
        "experiments/compute_ablation_bootstrap.py",
        REPO_ROOT / "experiments" / "results" / "ablation_20260601T232947",
        "ablation_bootstrap_*.json",
    )
    expected = json.loads((FIXTURES_DIR / "ablation_bootstrap_expected.json").read_text())
    assert actual == expected


def test_rq3_kappa_bootstrap_matches_golden_output() -> None:
    actual = _run_script_and_load_new_json(
        "experiments/compute_rq3_kappa_bootstrap.py",
        REPO_ROOT / "experiments" / "results",
        "rq3_kappa_bootstrap_*.json",
    )
    expected = json.loads((FIXTURES_DIR / "rq3_kappa_bootstrap_expected.json").read_text())
    assert actual == expected
